#!/usr/bin/python3
# coding=utf-8
import cv2
# 载入图像
im = cv2.imread('./1.jpg')
# OpenCV人脸识别分类器
classifier = cv2.CascadeClassifier("C:\\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml")
color = (0, 255, 0) # 定义绘制颜色
#调用识别人脸
faceRects = classifier.detectMultiScale( im, scaleFactor=1.2, minNeighbors=2, minSize=(32, 32))
print(faceRects)
if len(faceRects): # 大于0则检测到人脸
    for faceRect in faceRects: # 单独框出每一张人脸
        print(1);
        x, y, w, h = faceRect
         # 框出人脸
        cv2.rectangle(im, (x, y), (x + h, y + w), color, 2)  #在图像中绘制矩形
         # 左眼
        #cv2.circle(im, (x + w // 4, y + h // 4 + 30), min(w // 8, h // 8), color)
         #右眼
        #cv2.circle(im, (x + 3 * w // 4, y + h // 4 + 30), min(w // 8, h // 8), color)
         #嘴巴
       # cv2.rectangle(im, (x + 3 * w // 8, y + 3 * h // 4), (x + 5 * w // 8, y + 7 * h // 8), color)
cv2.imshow("image", im) # 显示图像
c = cv2.waitKey(10)
cv2.waitKey(0)
cv2.destroyAllWindows()
